Edited get started
ipld/website pull request #28
Opened 2016-12-16 23:09 UTC by RichardLitt

@nicola How does this look? Happy to keep going with this type of writing if it looks good!

2016-12-17 15:54 UTC, nicola requested changes

2016-12-17 15:54 UTC, nicola commented on Get-Started.md
> +This tutorial will teach you about how to use IPLD. We'll start from the very basics, and end with some examples.
I would prefer not to give the idea of "we teach you how to use our tools", but "you learn how to" or "we guide through". Does that make sense?

2016-12-17 15:54 UTC, nicola commented on Get-Started.md
> +IPLD stands for InterPlanetary Linked Data. This is based off of [IPFS](https://ipfs.io), which is the InterPlanetary File System. IPFS starts with a desire to have filesystems that work even when th
"interplanetary space travel!" :)
It is too exciting not to put a !
(your choice!)

2016-12-17 15:54 UTC, nicola commented on Get-Started.md
> +When we get data from the internet by accessing a webpage in our browser, we know it comes from the right place if the URL is https. This is because the HTTPS protocol gives some security that the da
" that the data hasn't been compromised, for instance by a man-in-the-middle attack" not sure

HTTPS gives guarantees that the data comes from the right place (the owner of the domain)

2016-12-17 15:54 UTC, nicola commented on Get-Started.md
> +Also importantly, it is impossible (well, really really difficult) to tell, given a hash, what content it refers to. That is why it is a one way function - data doesn't flow both ways. You also can't
"tell easily",
drop easily, you can't tell at all!

2016-12-23 15:18 UTC, RichardLitt commented on Get-Started.md
> +When we get data from the internet by accessing a webpage in our browser, we know it comes from the right place if the URL is https. This is because the HTTPS protocol gives some security that the da
Which is what a man in the middle attack would compromise. See opening paragraphs, here: https://en.wikipedia.org/wiki/HTTPS.

2016-12-23 15:51 UTC, RichardLitt commented
@nicola Added more edits.

2017-05-25 13:11 UTC, diasdavid commented
New website is now on this PR https://github.com/ipld/website/pull/30, closing this one.

2017-05-25 13:11 UTC, closed without merging